namespace PpmDecoderSharp.Test;

public class ReadImageTest
{
    [Theory]
    // P1
    [InlineData(Consts.ImagePathP1_1, 1, 200, 200, 1, "ASCII PBM file created by PBMA_WRITE.", "2399113CE95C46823B7F505908FBBD35610E8D7EE6D7929B55B2BFE0538D2AF5")]
    [InlineData(Consts.ImagePathP1_2, 1, 24, 7, 1, "feep.pbm", "124F8B6DA89837147EEB811819306B852059A7319AF7CFABD819145D190C4C60")]
    [InlineData(Consts.ImagePathP1_3, 1, 25, 25, 1, "letter_a.pbma", "22A8EF5F08EF71FD35F8E0C52F87569E93B564F45DE63166297B710D50BDDED3")]
    [InlineData(Consts.ImagePathP1_4, 1, 136, 82, 1, null, "A573390789482CB24E7C6A9B30D7AC14FF26EB1C29F4EC326B3766CE0EB59274")]
    // P2
    [InlineData(Consts.ImagePathP2_1, 2, 24, 7, 15, "feep.ascii.pgm", "F1406751120FEDD8B9FDFF2A1D5A18A5BFA6B35782E84C7D05FAAB388B63E51A")]
    [InlineData(Consts.ImagePathP2_2, 2, 300, 200, 252, "test02.pgm", "6A53FC21911F68AB814BC8BF38647E832ECE4BF592B1FCD3CB2CA63900BB40BD")]
    [InlineData(Consts.ImagePathP2_3, 2, 600, 600, 255, null, "8B57D24819E324640E44463EEA7896A1EABF2A1C5890C2F91D5BB6E4429473DF")]
    [InlineData(Consts.ImagePathP2_4, 2, 300, 246, 255, "fred.pgm created by PGMA_IO::PGMA_WRITE.", "FCBFB803C197DA62335C663EB6BA936C3E70E16D857B7A8AC7F4AD4081CD9774")]
    // P3
    [InlineData(Consts.ImagePathP3_1, 3, 300, 300, 255, "pbmlib.ppma created by PPMLIB(PPMA_WRITE).", "D9D73F807EE3C89D2AD521446F6D5BD71C9E71D970029E8E84BAA2E41AEA11F8")]
    [InlineData(Consts.ImagePathP3_2, 3, 256, 256, 255, "snail.ppm", "A4B36986C5E6B50B1BB465E889938ABA7FEEDB4FD73B70C7A37A02DE55A6AB82")]
    // P4
    [InlineData(Consts.ImagePathP4_1, 4, 25, 25, 1, "letter_a.pbma", "22A8EF5F08EF71FD35F8E0C52F87569E93B564F45DE63166297B710D50BDDED3")]
    [InlineData(Consts.ImagePathP4_2, 4, 24, 7, 1, "feep.pbm", "124F8B6DA89837147EEB811819306B852059A7319AF7CFABD819145D190C4C60")]
    [InlineData(Consts.ImagePathP4_3, 4, 136, 82, 1, null, "A573390789482CB24E7C6A9B30D7AC14FF26EB1C29F4EC326B3766CE0EB59274")]
    [InlineData(Consts.ImagePathP4_4, 4, 305, 400, 1, null, "204C8739C01A88A3E41D33840C8338C07D0AA720384F72D278EB2FC52A489203")]
    // P5
    [InlineData(Consts.ImagePathP5_1, 5, 24, 7, 15, null, "F1406751120FEDD8B9FDFF2A1D5A18A5BFA6B35782E84C7D05FAAB388B63E51A")]
    [InlineData(Consts.ImagePathP5_2, 5, 512, 512, 255, null, "3F71E592A10CBE0353CABA0344FB4012D3578A224D896E0A47806C8D0D98D1B9")]
    [InlineData(Consts.ImagePathP5_3, 5, 300, 246, 255, null, "FCBFB803C197DA62335C663EB6BA936C3E70E16D857B7A8AC7F4AD4081CD9774")]
    [InlineData(Consts.ImagePathP5_4, 5, 250, 360, 255, "CREATOR: GIMP PNM Filter Version 1.1", "CB0BE3B64E3C9FC1B0E8E45A9BBCD74812CC9F3554D5D1981F33A9CB87DD4177")]
    // P6
    [InlineData(Consts.ImagePathP6_1, 6, 258, 792, 255, "Image generated by Aladdin Ghostscript (device=ppmraw)", "E0DF4308528787C5DF89611A16119CCAA7031BC87C751B1BB0CD5437A038F775")]
    [InlineData(Consts.ImagePathP6_2, 6, 20, 10, 255, null, "5683DC6E4E226A9090378CD89895C463CE75FB269E40539B0E60255E9F73290B")]
    [InlineData(Consts.ImagePathP6_3, 6, 640, 426, 255, null, "FCCB8BEECD622C88DB474021ED7D3A266B72FFF351BB6CE2350045742CB7FC9C")]
    public async Task ReadImage_Success(string filePath,
        int formatNumber, int width, int height, int maxLevel, string? comment,
        string expectedHashString, CancellationToken cancellationToken = default)
    {
        var ppm = await PpmImage.ReadAsync(filePath, cancellationToken);
        Assert.NotNull(ppm);

        ppm.FormatNumber.Should().Be(formatNumber);
        ppm.Width.Should().Be(width);
        ppm.Height.Should().Be(height);
        ppm.MaxLevel.Should().Be(maxLevel);
        ppm.Comment.Should().Be(comment);

        var actualHash = new byte[32];    // 256bit=32Byte
        System.Security.Cryptography.SHA256.TryHashData(ppm.AsSpan(), actualHash, out int bytesWritten).Should().BeTrue();
        BitConverter.ToString(actualHash.AsSpan()[..bytesWritten].ToArray()).Replace("-", "").Should().Be(expectedHashString);
    }
}
